FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY fonts/NotoSansJP-Regular.ttf /usr/share/fonts/truetype/noto/NotoSansJP-Regular.ttf

COPY . .

CMD ["python", "-m", "app.workers.form_worker"]