"""remove field types

Revision ID: 005d8bdbcbae
Revises: aef1146d6525
Create Date: 2026-02-22 07:39:49.628943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005d8bdbcbae'
down_revision: Union[str, Sequence[str], None] = 'aef1146d6525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_fields', 'type')
    op.drop_column('report_template_fields', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_template_fields', sa.Column('type', postgresql.ENUM('string', 'number', 'boolean', 'date', name='reportfieldtype'), autoincrement=False, nullable=False))
    op.add_column('report_fields', sa.Column('type', postgresql.ENUM('string', 'number', 'boolean', 'date', name='reportfieldtype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
