"""add order

Revision ID: 00f8bea165ff
Revises: 005d8bdbcbae
Create Date: 2026-03-08 02:54:24.578163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f8bea165ff'
down_revision: Union[str, Sequence[str], None] = '005d8bdbcbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_fields', sa.Column('order', sa.Integer(), server_default="0", nullable=False))
    op.alter_column("report_fields", "order", server_default=None)
    op.add_column('report_template_fields', sa.Column('order', sa.Integer(), server_default="0", nullable=False))
    op.alter_column("report_template_fields", "order", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_template_fields', 'order')
    op.drop_column('report_fields', 'order')
    # ### end Alembic commands ###
