"""add image_descriptions_enabled

Revision ID: 044111c0c507
Revises: 20235e054dc1
Create Date: 2026-04-10 18:58:03.753391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044111c0c507'
down_revision: Union[str, Sequence[str], None] = '20235e054dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('image_descriptions_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'image_descriptions_enabled')
    # ### end Alembic commands ###
