"""add id to report image tag link

Revision ID: 098604d823c7
Revises: ffa099106ccf
Create Date: 2026-03-27 08:05:37.660740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098604d823c7'
down_revision: Union[str, Sequence[str], None] = 'ffa099106ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_image_tag_links', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_image_tag_links', 'id')
    # ### end Alembic commands ###
