"""line timestamp

Revision ID: 0c97bbcb88cb
Revises: b2a8bca9c50b
Create Date: 2026-07-06 01:04:26.640339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c97bbcb88cb'
down_revision: Union[str, Sequence[str], None] = 'b2a8bca9c50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_messages', sa.Column('line_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_messages', 'line_timestamp')
    # ### end Alembic commands ###
