"""custom relationship fixes

Revision ID: 1292575ce0bd
Revises: 18816542c564
Create Date: 2026-08-18 20:03:14.919553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1292575ce0bd'
down_revision: Union[str, Sequence[str], None] = '18816542c564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_relationship_definitions', sa.Column('source_custom_object_definition_id', sa.UUID(), nullable=True))
    op.add_column('custom_relationship_definitions', sa.Column('target_custom_object_definition_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_custom_relationship_definitions_source_custom_object_definition_id'), 'custom_relationship_definitions', ['source_custom_object_definition_id'], unique=False)
    op.create_index(op.f('ix_custom_relationship_definitions_target_custom_object_definition_id'), 'custom_relationship_definitions', ['target_custom_object_definition_id'], unique=False)
    op.create_foreign_key(None, 'custom_relationship_definitions', 'custom_object_definitions', ['target_custom_object_definition_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'custom_relationship_definitions', 'custom_object_definitions', ['source_custom_object_definition_id'], ['id'], ondelete='CASCADE')
    op.add_column('custom_relationships', sa.Column('source_custom_object_definition_id', sa.UUID(), nullable=True))
    op.add_column('custom_relationships', sa.Column('target_custom_object_definition_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_custom_relationships_source_custom_object_definition_id'), 'custom_relationships', ['source_custom_object_definition_id'], unique=False)
    op.create_index(op.f('ix_custom_relationships_target_custom_object_definition_id'), 'custom_relationships', ['target_custom_object_definition_id'], unique=False)
    op.create_foreign_key(None, 'custom_relationships', 'custom_object_definitions', ['target_custom_object_definition_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'custom_relationships', 'custom_object_definitions', ['source_custom_object_definition_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_relationships', type_='foreignkey')
    op.drop_constraint(None, 'custom_relationships', type_='foreignkey')
    op.drop_index(op.f('ix_custom_relationships_target_custom_object_definition_id'), table_name='custom_relationships')
    op.drop_index(op.f('ix_custom_relationships_source_custom_object_definition_id'), table_name='custom_relationships')
    op.drop_column('custom_relationships', 'target_custom_object_definition_id')
    op.drop_column('custom_relationships', 'source_custom_object_definition_id')
    op.drop_constraint(None, 'custom_relationship_definitions', type_='foreignkey')
    op.drop_constraint(None, 'custom_relationship_definitions', type_='foreignkey')
    op.drop_index(op.f('ix_custom_relationship_definitions_target_custom_object_definition_id'), table_name='custom_relationship_definitions')
    op.drop_index(op.f('ix_custom_relationship_definitions_source_custom_object_definition_id'), table_name='custom_relationship_definitions')
    op.drop_column('custom_relationship_definitions', 'target_custom_object_definition_id')
    op.drop_column('custom_relationship_definitions', 'source_custom_object_definition_id')
    # ### end Alembic commands ###
