"""line timestamp on action item

Revision ID: 1417655d2746
Revises: 0c97bbcb88cb
Create Date: 2026-07-06 01:08:09.554900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1417655d2746'
down_revision: Union[str, Sequence[str], None] = '0c97bbcb88cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_items', sa.Column('line_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_items', 'line_timestamp')
    # ### end Alembic commands ###
