"""remove user and project line link codes

Revision ID: 14670e1e3493
Revises: ae234f1ba772
Create Date: 2026-07-16 03:04:29.257117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14670e1e3493'
down_revision: Union[str, Sequence[str], None] = 'ae234f1ba772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_line_links_line_user_id'), table_name='user_line_links')
    op.drop_table('user_line_links')
    op.drop_index(op.f('ix_projects_line_group_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_line_link_code'), table_name='projects')
    op.drop_column('projects', 'line_link_code')
    op.drop_column('projects', 'line_group_id')
    op.drop_index(op.f('ix_users_line_link_code'), table_name='users')
    op.drop_column('users', 'line_link_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('line_link_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_line_link_code'), 'users', ['line_link_code'], unique=True)
    op.add_column('projects', sa.Column('line_group_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('line_link_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_projects_line_link_code'), 'projects', ['line_link_code'], unique=True)
    op.create_index(op.f('ix_projects_line_group_id'), 'projects', ['line_group_id'], unique=True)
    op.create_table('user_line_links',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('line_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('user_line_links_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_line_links_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_line_links_pkey')),
    sa.UniqueConstraint('company_id', 'line_user_id', name=op.f('uq_user_line_link_company_line_user'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', 'company_id', name=op.f('uq_user_line_link_user_company'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_line_links_line_user_id'), 'user_line_links', ['line_user_id'], unique=False)
    # ### end Alembic commands ###
