"""assignee

Revision ID: 154bcc859379
Revises: 1a015f57a84f
Create Date: 2026-08-06 19:14:07.683339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154bcc859379'
down_revision: Union[str, Sequence[str], None] = '1a015f57a84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_items', sa.Column('assignee_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_conversation_items_assignee_id'), 'conversation_items', ['assignee_id'], unique=False)
    op.create_foreign_key(None, 'conversation_items', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_items', type_='foreignkey')
    op.drop_index(op.f('ix_conversation_items_assignee_id'), table_name='conversation_items')
    op.drop_column('conversation_items', 'assignee_id')
    # ### end Alembic commands ###
