"""rm parent_id and parent_type

Revision ID: 1a015f57a84f
Revises: 380db5d9dbed
Create Date: 2026-08-04 00:58:04.767934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a015f57a84f'
down_revision: Union[str, Sequence[str], None] = '380db5d9dbed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("DELETE FROM report_image_links")
    op.execute("DELETE FROM report_fields")
    op.execute("DELETE FROM reports")

    op.create_table('report_project_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'project_id', name='uq_report_project_link')
    )
    op.create_index(op.f('ix_report_project_links_id'), 'report_project_links', ['id'], unique=False)
    op.create_index(op.f('ix_report_project_links_project_id'), 'report_project_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_report_project_links_report_id'), 'report_project_links', ['report_id'], unique=False)
    op.drop_column('report_templates', 'parent_type')
    op.add_column('reports', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_reports_parent'), table_name='reports')
    op.create_index(op.f('ix_reports_company_id'), 'reports', ['company_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reports', 'parent_id')
    op.drop_column('reports', 'parent_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('parent_type', postgresql.ENUM('project', 'company', name='reportparenttype'), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_company_id'), table_name='reports')
    op.create_index(op.f('ix_reports_parent'), 'reports', ['parent_type', 'parent_id'], unique=False)
    op.drop_column('reports', 'company_id')
    op.add_column('report_templates', sa.Column('parent_type', postgresql.ENUM('project', 'company', name='reportparenttype'), server_default=sa.text("'project'::reportparenttype"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_report_project_links_report_id'), table_name='report_project_links')
    op.drop_index(op.f('ix_report_project_links_project_id'), table_name='report_project_links')
    op.drop_index(op.f('ix_report_project_links_id'), table_name='report_project_links')
    op.drop_table('report_project_links')
    # ### end Alembic commands ###
