"""add parent type to report template

Revision ID: 1ffba63c21d5
Revises: 75f17dc18a30
Create Date: 2026-02-10 22:36:22.744137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffba63c21d5'
down_revision: Union[str, Sequence[str], None] = '75f17dc18a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_templates', sa.Column('parent_type', sa.Enum('project', 'company', name='reportparenttype'), nullable=False, server_default='project'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_templates', 'parent_type')
    # ### end Alembic commands ###
