"""remove unique by

Revision ID: 20235e054dc1
Revises: ee4acb3866a4
Create Date: 2026-04-08 23:51:39.521848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20235e054dc1'
down_revision: Union[str, Sequence[str], None] = 'ee4acb3866a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_templates', 'unique_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_templates', sa.Column('unique_by', postgresql.ENUM('day', 'week', 'month', 'year', name='report_unique_by'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
