"""drop line fields from company

Revision ID: 294479a428ec
Revises: 599728859323
Create Date: 2026-06-18 08:26:15.258589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294479a428ec'
down_revision: Union[str, Sequence[str], None] = '599728859323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'line_channel_access_token')
    op.drop_column('companies', 'line_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('line_channel_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('line_channel_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
