"""add company to image

Revision ID: 3781bb9779cf
Revises: f466f96cbc22
Create Date: 2026-07-29 00:17:35.611366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3781bb9779cf'
down_revision: Union[str, Sequence[str], None] = 'f466f96cbc22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_images_company_id'), 'images', ['company_id'], unique=False)
    op.create_foreign_key(None, 'images', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_index(op.f('ix_images_company_id'), table_name='images')
    op.drop_column('images', 'company_id')
    # ### end Alembic commands ###
