"""add company to image

Revision ID: 3781bb9779cf
Revises: f466f96cbc22
Create Date: 2026-07-29 00:17:35.611366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3781bb9779cf'
down_revision: Union[str, Sequence[str], None] = 'f466f96cbc22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_images_company_id'), 'images', ['company_id'], unique=False)
    op.create_foreign_key(None, 'images', 'companies', ['company_id'], ['id'])

    op.execute("""
DELETE FROM image_tag_links
WHERE image_id IN (
    SELECT i.id
    FROM images i
    LEFT JOIN report_image_links ril
      ON ril.image_id = i.id
    WHERE ril.image_id IS NULL
);
""")

    op.execute("""
DELETE FROM images
WHERE id IN (
    SELECT i.id
    FROM images i
    LEFT JOIN report_image_links ril
      ON ril.image_id = i.id
    WHERE ril.image_id IS NULL
);
""")

    op.execute("""
UPDATE images i
SET company_id = c.id
FROM report_image_links ril
JOIN reports r
  ON ril.report_id = r.id
LEFT JOIN projects p
  ON r.parent_type = 'project'
 AND r.parent_id = p.id
JOIN companies c
  ON (
       (r.parent_type = 'company' AND r.parent_id = c.id)
    OR (r.parent_type = 'project' AND p.company_id = c.id)
  )
WHERE ril.image_id = i.id;
""")

    op.alter_column("images", "company_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_index(op.f('ix_images_company_id'), table_name='images')
    op.drop_column('images', 'company_id')
    # ### end Alembic commands ###
