"""user line link

Revision ID: 39382da18c6d
Revises: 8ae362fc4ccd
Create Date: 2026-06-19 12:01:12.551471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39382da18c6d'
down_revision: Union[str, Sequence[str], None] = '8ae362fc4ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_line_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('line_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'line_user_id', name='uq_user_line_link_company_line_user'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_line_link_user_company')
    )
    op.create_index(op.f('ix_user_line_links_line_user_id'), 'user_line_links', ['line_user_id'], unique=False)
    op.execute("""
        UPDATE users
        SET line_link_code = 'K-' || (
            SELECT string_agg(
                substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', (get_byte(digest, i) % 32) + 1, 1),
                ''
                ORDER BY i
            )
            FROM generate_series(0, 5) AS i,
            LATERAL (SELECT sha256(id::text::bytea) AS digest) AS d
        )
        WHERE line_link_code IS NULL
    """)
    op.alter_column('users', 'line_link_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_line_user_id'), table_name='users')
    op.drop_column('users', 'line_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('line_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_line_user_id'), 'users', ['line_user_id'], unique=True)
    op.alter_column('users', 'line_link_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_user_line_links_line_user_id'), table_name='user_line_links')
    op.drop_table('user_line_links')
    # ### end Alembic commands ###
