"""change cardinality

Revision ID: 39accf019af9
Revises: 54761de3580a
Create Date: 2026-08-18 18:28:44.118517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39accf019af9'
down_revision: Union[str, Sequence[str], None] = '54761de3580a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_relationship_definitions', sa.Column('cardinality', sa.Enum('one', 'many', name='custom_relationship_cardinality'), nullable=False))
    op.drop_column('custom_relationship_definitions', 'target_cardinality')
    op.drop_column('custom_relationship_definitions', 'source_cardinality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_relationship_definitions', sa.Column('source_cardinality', postgresql.ENUM('one', 'many', name='custom_relationship_cardinality'), autoincrement=False, nullable=False))
    op.add_column('custom_relationship_definitions', sa.Column('target_cardinality', postgresql.ENUM('one', 'many', name='custom_relationship_cardinality'), autoincrement=False, nullable=False))
    op.drop_column('custom_relationship_definitions', 'cardinality')
    # ### end Alembic commands ###
