"""add stripe fields to company

Revision ID: 42952d2b6fef
Revises: 5592f3bc7d5b
Create Date: 2026-06-10 22:25:47.725340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42952d2b6fef'
down_revision: Union[str, Sequence[str], None] = '5592f3bc7d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('stripe_subscription_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_stripe_customer_id'), 'companies', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_companies_stripe_subscription_id'), 'companies', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_stripe_subscription_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_stripe_customer_id'), table_name='companies')
    op.drop_column('companies', 'stripe_subscription_status')
    op.drop_column('companies', 'stripe_subscription_id')
    op.drop_column('companies', 'stripe_customer_id')
    # ### end Alembic commands ###
