"""remove conversation item type unique name constraint

Revision ID: 474519fb3cfb
Revises: 1f7464930ee6
Create Date: 2026-07-16 20:15:35.199815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474519fb3cfb'
down_revision: Union[str, Sequence[str], None] = '1f7464930ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_conversation_item_type_company_name'), 'conversation_item_types', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_conversation_item_type_company_name'), 'conversation_item_types', ['company_id', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
