"""add report image links

Revision ID: 481d8a2085c2
Revises: 1e6d249f86f6
Create Date: 2026-07-27 16:05:57.806057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481d8a2085c2'
down_revision: Union[str, Sequence[str], None] = '1e6d249f86f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_image_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'image_id', name='uq_report_image')
    )
    op.create_index(op.f('ix_report_image_links_image_id'), 'report_image_links', ['image_id'], unique=False)
    op.create_index(op.f('ix_report_image_links_report_id'), 'report_image_links', ['report_id'], unique=False)
    op.drop_constraint(op.f('report_images_report_id_fkey'), 'images', type_='foreignkey')
    op.drop_column('images', 'report_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('report_images_report_id_fkey'), 'images', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_report_image_links_report_id'), table_name='report_image_links')
    op.drop_index(op.f('ix_report_image_links_image_id'), table_name='report_image_links')
    op.drop_table('report_image_links')
    # ### end Alembic commands ###
