"""remove stripe subscription status

Revision ID: 4948ba5a4791
Revises: 1417655d2746
Create Date: 2026-07-13 01:30:55.830251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4948ba5a4791'
down_revision: Union[str, Sequence[str], None] = '1417655d2746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'stripe_subscription_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('stripe_subscription_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
