"""add report image status

Revision ID: 50102249365f
Revises: c4841460e711
Create Date: 2026-03-13 02:31:04.573523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50102249365f'
down_revision: Union[str, Sequence[str], None] = 'c4841460e711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_company_tag_name', 'report_image_tags', ['company_id', 'name'])
    op.add_column('report_images', sa.Column('status', sa.String(), nullable=False))
    op.drop_index(op.f('ix_report_images_report_id'), table_name='report_images')
    op.drop_column('report_images', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_images', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_report_images_report_id'), 'report_images', ['report_id'], unique=False)
    op.drop_column('report_images', 'status')
    op.drop_constraint('uq_company_tag_name', 'report_image_tags', type_='unique')
    # ### end Alembic commands ###
