"""remove name and description

Revision ID: 517c5818ef37
Revises: b575409a7603
Create Date: 2026-08-20 23:56:11.768411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517c5818ef37'
down_revision: Union[str, Sequence[str], None] = 'b575409a7603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_objects', 'name')
    op.drop_column('custom_objects', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_objects', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('custom_objects', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
