"""more forms fields

Revision ID: 54761de3580a
Revises: 563951dae33c
Create Date: 2026-08-18 01:41:10.732056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54761de3580a'
down_revision: Union[str, Sequence[str], None] = '563951dae33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'key', name='uq_custom_field_definition_company_key')
    )
    op.create_index(op.f('ix_custom_field_definitions_company_id'), 'custom_field_definitions', ['company_id'], unique=False)
    op.create_index(op.f('ix_custom_field_definitions_id'), 'custom_field_definitions', ['id'], unique=False)
    op.create_table('custom_object_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_object_definitions_company_id'), 'custom_object_definitions', ['company_id'], unique=False)
    op.create_index(op.f('ix_custom_object_definitions_id'), 'custom_object_definitions', ['id'], unique=False)
    op.create_table('custom_relationship_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_entity_type', sa.Enum('company', 'user', 'project', 'custom_object', name='custom_relationship_entity_type'), nullable=False),
    sa.Column('target_entity_type', sa.Enum('company', 'user', 'project', 'custom_object', name='custom_relationship_entity_type'), nullable=False),
    sa.Column('source_cardinality', sa.Enum('one', 'many', name='custom_relationship_cardinality'), nullable=False),
    sa.Column('target_cardinality', sa.Enum('one', 'many', name='custom_relationship_cardinality'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'key', name='uq_custom_relationship_definition_company_key')
    )
    op.create_index(op.f('ix_custom_relationship_definitions_company_id'), 'custom_relationship_definitions', ['company_id'], unique=False)
    op.create_index(op.f('ix_custom_relationship_definitions_id'), 'custom_relationship_definitions', ['id'], unique=False)
    op.create_table('custom_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('custom_field_definition_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custom_field_definition_id'], ['custom_field_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_fields_company_id'), 'custom_fields', ['company_id'], unique=False)
    op.create_index(op.f('ix_custom_fields_custom_field_definition_id'), 'custom_fields', ['custom_field_definition_id'], unique=False)
    op.create_index(op.f('ix_custom_fields_id'), 'custom_fields', ['id'], unique=False)
    op.create_table('custom_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('custom_object_definition_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custom_object_definition_id'], ['custom_object_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_objects_company_id'), 'custom_objects', ['company_id'], unique=False)
    op.create_index(op.f('ix_custom_objects_custom_object_definition_id'), 'custom_objects', ['custom_object_definition_id'], unique=False)
    op.create_index(op.f('ix_custom_objects_id'), 'custom_objects', ['id'], unique=False)
    op.create_table('custom_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('custom_relationship_definition_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_type', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_type', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custom_relationship_definition_id'], ['custom_relationship_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_relationship_definition_id', 'source_entity_id', 'target_entity_id', name='uq_custom_relationship')
    )
    op.create_index(op.f('ix_custom_relationships_company_id'), 'custom_relationships', ['company_id'], unique=False)
    op.create_index(op.f('ix_custom_relationships_custom_relationship_definition_id'), 'custom_relationships', ['custom_relationship_definition_id'], unique=False)
    op.create_index(op.f('ix_custom_relationships_id'), 'custom_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_custom_relationships_source_entity_id'), 'custom_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_custom_relationships_target_entity_id'), 'custom_relationships', ['target_entity_id'], unique=False)
    op.create_table('project_user_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_project_user')
    )
    op.create_index(op.f('ix_project_user_links_id'), 'project_user_links', ['id'], unique=False)
    op.create_index(op.f('ix_project_user_links_project_id'), 'project_user_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_user_links_user_id'), 'project_user_links', ['user_id'], unique=False)
    op.create_table('custom_field_company_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_field_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_field_id', 'company_id', name='uq_custom_field_company_link')
    )
    op.create_index(op.f('ix_custom_field_company_links_company_id'), 'custom_field_company_links', ['company_id'], unique=False)
    op.create_index(op.f('ix_custom_field_company_links_custom_field_id'), 'custom_field_company_links', ['custom_field_id'], unique=False)
    op.create_index(op.f('ix_custom_field_company_links_id'), 'custom_field_company_links', ['id'], unique=False)
    op.create_table('custom_field_custom_object_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_field_id', sa.UUID(), nullable=False),
    sa.Column('custom_object_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custom_object_id'], ['custom_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_field_id', 'custom_object_id', name='uq_custom_field_custom_object_link')
    )
    op.create_index(op.f('ix_custom_field_custom_object_links_custom_field_id'), 'custom_field_custom_object_links', ['custom_field_id'], unique=False)
    op.create_index(op.f('ix_custom_field_custom_object_links_custom_object_id'), 'custom_field_custom_object_links', ['custom_object_id'], unique=False)
    op.create_index(op.f('ix_custom_field_custom_object_links_id'), 'custom_field_custom_object_links', ['id'], unique=False)
    op.create_table('custom_field_project_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_field_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_field_id', 'project_id', name='uq_custom_field_project_link')
    )
    op.create_index(op.f('ix_custom_field_project_links_custom_field_id'), 'custom_field_project_links', ['custom_field_id'], unique=False)
    op.create_index(op.f('ix_custom_field_project_links_id'), 'custom_field_project_links', ['id'], unique=False)
    op.create_index(op.f('ix_custom_field_project_links_project_id'), 'custom_field_project_links', ['project_id'], unique=False)
    op.create_table('custom_field_user_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_field_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_field_id', 'user_id', name='uq_custom_field_user_link')
    )
    op.create_index(op.f('ix_custom_field_user_links_custom_field_id'), 'custom_field_user_links', ['custom_field_id'], unique=False)
    op.create_index(op.f('ix_custom_field_user_links_id'), 'custom_field_user_links', ['id'], unique=False)
    op.create_index(op.f('ix_custom_field_user_links_user_id'), 'custom_field_user_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_field_user_links_user_id'), table_name='custom_field_user_links')
    op.drop_index(op.f('ix_custom_field_user_links_id'), table_name='custom_field_user_links')
    op.drop_index(op.f('ix_custom_field_user_links_custom_field_id'), table_name='custom_field_user_links')
    op.drop_table('custom_field_user_links')
    op.drop_index(op.f('ix_custom_field_project_links_project_id'), table_name='custom_field_project_links')
    op.drop_index(op.f('ix_custom_field_project_links_id'), table_name='custom_field_project_links')
    op.drop_index(op.f('ix_custom_field_project_links_custom_field_id'), table_name='custom_field_project_links')
    op.drop_table('custom_field_project_links')
    op.drop_index(op.f('ix_custom_field_custom_object_links_id'), table_name='custom_field_custom_object_links')
    op.drop_index(op.f('ix_custom_field_custom_object_links_custom_object_id'), table_name='custom_field_custom_object_links')
    op.drop_index(op.f('ix_custom_field_custom_object_links_custom_field_id'), table_name='custom_field_custom_object_links')
    op.drop_table('custom_field_custom_object_links')
    op.drop_index(op.f('ix_custom_field_company_links_id'), table_name='custom_field_company_links')
    op.drop_index(op.f('ix_custom_field_company_links_custom_field_id'), table_name='custom_field_company_links')
    op.drop_index(op.f('ix_custom_field_company_links_company_id'), table_name='custom_field_company_links')
    op.drop_table('custom_field_company_links')
    op.drop_index(op.f('ix_project_user_links_user_id'), table_name='project_user_links')
    op.drop_index(op.f('ix_project_user_links_project_id'), table_name='project_user_links')
    op.drop_index(op.f('ix_project_user_links_id'), table_name='project_user_links')
    op.drop_table('project_user_links')
    op.drop_index(op.f('ix_custom_relationships_target_entity_id'), table_name='custom_relationships')
    op.drop_index(op.f('ix_custom_relationships_source_entity_id'), table_name='custom_relationships')
    op.drop_index(op.f('ix_custom_relationships_id'), table_name='custom_relationships')
    op.drop_index(op.f('ix_custom_relationships_custom_relationship_definition_id'), table_name='custom_relationships')
    op.drop_index(op.f('ix_custom_relationships_company_id'), table_name='custom_relationships')
    op.drop_table('custom_relationships')
    op.drop_index(op.f('ix_custom_objects_id'), table_name='custom_objects')
    op.drop_index(op.f('ix_custom_objects_custom_object_definition_id'), table_name='custom_objects')
    op.drop_index(op.f('ix_custom_objects_company_id'), table_name='custom_objects')
    op.drop_table('custom_objects')
    op.drop_index(op.f('ix_custom_fields_id'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_custom_field_definition_id'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_company_id'), table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index(op.f('ix_custom_relationship_definitions_id'), table_name='custom_relationship_definitions')
    op.drop_index(op.f('ix_custom_relationship_definitions_company_id'), table_name='custom_relationship_definitions')
    op.drop_table('custom_relationship_definitions')
    op.drop_index(op.f('ix_custom_object_definitions_id'), table_name='custom_object_definitions')
    op.drop_index(op.f('ix_custom_object_definitions_company_id'), table_name='custom_object_definitions')
    op.drop_table('custom_object_definitions')
    op.drop_index(op.f('ix_custom_field_definitions_id'), table_name='custom_field_definitions')
    op.drop_index(op.f('ix_custom_field_definitions_company_id'), table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    # ### end Alembic commands ###
