"""add project invitation changes

Revision ID: 5592f3bc7d5b
Revises: c76e26fecd0a
Create Date: 2026-06-01 12:27:57.332040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5592f3bc7d5b'
down_revision: Union[str, Sequence[str], None] = 'c76e26fecd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_guest_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_project_guest_user')
    )
    op.create_index(op.f('ix_project_guest_links_project_id'), 'project_guest_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_guest_links_user_id'), 'project_guest_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_guest_links_user_id'), table_name='project_guest_links')
    op.drop_index(op.f('ix_project_guest_links_project_id'), table_name='project_guest_links')
    op.drop_table('project_guest_links')
    # ### end Alembic commands ###
