"""billing plan fix

Revision ID: 55bac9ff6052
Revises: 5cbe570c070f
Create Date: 2026-07-01 06:14:44.098638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bac9ff6052'
down_revision: Union[str, Sequence[str], None] = '5cbe570c070f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=False),
    sa.Column('amount_jpy', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_price_id')
    )
    op.add_column('companies', sa.Column('billing_plan_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'companies', 'billing_plans', ['billing_plan_id'], ['id'])
    op.drop_column('companies', 'billing_exempt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('billing_exempt', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'billing_plan_id')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
