"""add corporate number

Revision ID: 5740c0935ca8
Revises: 78c577e3bb92
Create Date: 2026-02-03 21:34:55.529766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5740c0935ca8'
down_revision: Union[str, Sequence[str], None] = '78c577e3bb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('corporate_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_corporate_number'), 'companies', ['corporate_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_corporate_number'), table_name='companies')
    op.drop_column('companies', 'corporate_number')
    # ### end Alembic commands ###
