"""add line fields to company

Revision ID: 599728859323
Revises: 3cfce01796f8
Create Date: 2026-06-17 11:22:59.046758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599728859323'
down_revision: Union[str, Sequence[str], None] = '3cfce01796f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('line_channel_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('line_channel_secret', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('line_channel_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'line_channel_access_token')
    op.drop_column('companies', 'line_channel_secret')
    op.drop_column('companies', 'line_channel_id')
    # ### end Alembic commands ###
