"""remove key

Revision ID: 59e1e89fc3c5
Revises: 66fd9b9a6ca2
Create Date: 2026-08-19 07:29:01.676786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e1e89fc3c5'
down_revision: Union[str, Sequence[str], None] = '66fd9b9a6ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_custom_field_definition_company_key'), 'custom_field_definitions', type_='unique')
    op.drop_column('custom_field_definitions', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field_definitions', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_custom_field_definition_company_key'), 'custom_field_definitions', ['company_id', 'key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
