"""conversations

Revision ID: 5bac3d33ce35
Revises: 4948ba5a4791
Create Date: 2026-07-14 21:14:52.740935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bac3d33ce35'
down_revision: Union[str, Sequence[str], None] = '4948ba5a4791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_item_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_conversation_item_type_company_name')
    )
    op.create_index(op.f('ix_conversation_item_types_company_id'), 'conversation_item_types', ['company_id'], unique=False)
    op.create_index(op.f('ix_conversation_item_types_id'), 'conversation_item_types', ['id'], unique=False)
    op.create_table('line_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('line_link_code', sa.String(), nullable=False),
    sa.Column('line_group_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_conversations_company_id'), 'line_conversations', ['company_id'], unique=False)
    op.create_index(op.f('ix_line_conversations_id'), 'line_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_line_conversations_line_group_id'), 'line_conversations', ['line_group_id'], unique=True)
    op.create_index(op.f('ix_line_conversations_line_link_code'), 'line_conversations', ['line_link_code'], unique=True)
    op.create_index(op.f('ix_line_conversations_project_id'), 'line_conversations', ['project_id'], unique=False)
    op.create_table('conversation_item_type_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('item_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['line_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_type_id'], ['conversation_item_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'item_type_id', name='uq_conversation_item_type_link')
    )
    op.create_index(op.f('ix_conversation_item_type_links_conversation_id'), 'conversation_item_type_links', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_item_type_links_item_type_id'), 'conversation_item_type_links', ['item_type_id'], unique=False)
    op.create_table('conversation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('conversation_item_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_message_text', sa.String(), nullable=True),
    sa.Column('line_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['line_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_item_type_id'], ['conversation_item_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_items_conversation_id'), 'conversation_items', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_items_conversation_item_type_id'), 'conversation_items', ['conversation_item_type_id'], unique=False)
    op.create_index(op.f('ix_conversation_items_id'), 'conversation_items', ['id'], unique=False)
    op.add_column('line_messages', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_line_messages_conversation_id'), 'line_messages', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'line_messages', 'line_conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'line_messages', type_='foreignkey')
    op.drop_index(op.f('ix_line_messages_conversation_id'), table_name='line_messages')
    op.drop_column('line_messages', 'conversation_id')
    op.drop_index(op.f('ix_conversation_items_id'), table_name='conversation_items')
    op.drop_index(op.f('ix_conversation_items_conversation_item_type_id'), table_name='conversation_items')
    op.drop_index(op.f('ix_conversation_items_conversation_id'), table_name='conversation_items')
    op.drop_table('conversation_items')
    op.drop_index(op.f('ix_conversation_item_type_links_item_type_id'), table_name='conversation_item_type_links')
    op.drop_index(op.f('ix_conversation_item_type_links_conversation_id'), table_name='conversation_item_type_links')
    op.drop_table('conversation_item_type_links')
    op.drop_index(op.f('ix_line_conversations_project_id'), table_name='line_conversations')
    op.drop_index(op.f('ix_line_conversations_line_link_code'), table_name='line_conversations')
    op.drop_index(op.f('ix_line_conversations_line_group_id'), table_name='line_conversations')
    op.drop_index(op.f('ix_line_conversations_id'), table_name='line_conversations')
    op.drop_index(op.f('ix_line_conversations_company_id'), table_name='line_conversations')
    op.drop_table('line_conversations')
    op.drop_index(op.f('ix_conversation_item_types_id'), table_name='conversation_item_types')
    op.drop_index(op.f('ix_conversation_item_types_company_id'), table_name='conversation_item_types')
    op.drop_table('conversation_item_types')
    # ### end Alembic commands ###
