"""add billing fields to company

Revision ID: 66efaa2b9adc
Revises: 42952d2b6fef
Create Date: 2026-06-14 00:22:23.407918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66efaa2b9adc'
down_revision: Union[str, Sequence[str], None] = '42952d2b6fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('has_payment_method', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('companies', sa.Column('billing_exempt', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'billing_exempt')
    op.drop_column('companies', 'has_payment_method')
    # ### end Alembic commands ###
