"""entity type

Revision ID: 66fd9b9a6ca2
Revises: e0cc04799a0b
Create Date: 2026-08-18 21:36:35.321717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fd9b9a6ca2'
down_revision: Union[str, Sequence[str], None] = 'e0cc04799a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field_definitions', sa.Column('entity_type', sa.String(), nullable=False))
    op.add_column('custom_field_definitions', sa.Column('custom_object_definition_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_custom_field_definitions_custom_object_definition_id'), 'custom_field_definitions', ['custom_object_definition_id'], unique=False)
    op.create_foreign_key(None, 'custom_field_definitions', 'custom_object_definitions', ['custom_object_definition_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_field_definitions', type_='foreignkey')
    op.drop_index(op.f('ix_custom_field_definitions_custom_object_definition_id'), table_name='custom_field_definitions')
    op.drop_column('custom_field_definitions', 'custom_object_definition_id')
    op.drop_column('custom_field_definitions', 'entity_type')
    # ### end Alembic commands ###
