"""add line channel access token to company

Revision ID: 67260481971b
Revises: 8cde09fab76d
Create Date: 2026-07-26 14:26:27.737698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67260481971b'
down_revision: Union[str, Sequence[str], None] = '8cde09fab76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('line_channel_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'line_channel_access_token')
    # ### end Alembic commands ###
