"""company kill switch

Revision ID: 74d756a126ed
Revises: c3d53e109019
Create Date: 2026-08-09 06:22:01.411363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d756a126ed'
down_revision: Union[str, Sequence[str], None] = 'c3d53e109019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('paid_features_force_disabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'paid_features_force_disabled')
    # ### end Alembic commands ###
