"""add name to report field

Revision ID: 75f17dc18a30
Revises: 33f91dedd7a9
Create Date: 2026-02-10 00:42:36.993500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f17dc18a30'
down_revision: Union[str, Sequence[str], None] = '33f91dedd7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_fields', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_fields', 'name')
    # ### end Alembic commands ###
