"""remove can_create_projects

Revision ID: 78c577e3bb92
Revises: c6315d0765ca
Create Date: 2026-02-02 19:14:54.147263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c577e3bb92'
down_revision: Union[str, Sequence[str], None] = 'c6315d0765ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'can_create_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('can_create_projects', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
