"""add line link to user

Revision ID: 8ae362fc4ccd
Revises: 294479a428ec
Create Date: 2026-06-19 06:42:25.886092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae362fc4ccd'
down_revision: Union[str, Sequence[str], None] = '294479a428ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('line_user_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('line_link_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_line_link_code'), 'users', ['line_link_code'], unique=True)
    op.create_index(op.f('ix_users_line_user_id'), 'users', ['line_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_line_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_line_link_code'), table_name='users')
    op.drop_column('users', 'line_link_code')
    op.drop_column('users', 'line_user_id')
    # ### end Alembic commands ###
