"""image processing type

Revision ID: 8cde09fab76d
Revises: 92c8214b215b
Create Date: 2026-07-22 20:12:28.032238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cde09fab76d'
down_revision: Union[str, Sequence[str], None] = '92c8214b215b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_images', sa.Column('processing_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_images', 'processing_type')
    # ### end Alembic commands ###
