"""create form jobs

Revision ID: 90c8c365f69f
Revises: f14c1f68e5f3
Create Date: 2026-08-25 18:36:36.791539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c8c365f69f'
down_revision: Union[str, Sequence[str], None] = 'f14c1f68e5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'needs_review', 'failed', name='form_job_status'), nullable=False),
    sa.Column('origin', sa.Enum('web', 'email', 'api', name='form_job_origin'), nullable=False),
    sa.Column('origin_id', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_jobs_company_id'), 'form_jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_form_jobs_id'), 'form_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_form_jobs_project_id'), 'form_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_form_jobs_status'), 'form_jobs', ['status'], unique=False)
    op.create_table('form_job_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_job_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('is_input', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_job_id'], ['form_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_job_files_form_job_id'), 'form_job_files', ['form_job_id'], unique=False)
    op.create_index(op.f('ix_form_job_files_id'), 'form_job_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_job_files_id'), table_name='form_job_files')
    op.drop_index(op.f('ix_form_job_files_form_job_id'), table_name='form_job_files')
    op.drop_table('form_job_files')
    op.drop_index(op.f('ix_form_jobs_status'), table_name='form_jobs')
    op.drop_index(op.f('ix_form_jobs_project_id'), table_name='form_jobs')
    op.drop_index(op.f('ix_form_jobs_id'), table_name='form_jobs')
    op.drop_index(op.f('ix_form_jobs_company_id'), table_name='form_jobs')
    op.drop_table('form_jobs')
    # ### end Alembic commands ###
