"""add line chat type to conversation

Revision ID: 92c8214b215b
Revises: e04313f40c98
Create Date: 2026-07-19 09:28:40.871941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c8214b215b'
down_revision: Union[str, Sequence[str], None] = 'e04313f40c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_conversations', sa.Column('line_chat_type', sa.Enum('user', 'group', 'room', name='linechattype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_conversations', 'line_chat_type')
    # ### end Alembic commands ###
