"""line message attachments

Revision ID: 937ff52a491b
Revises: 67260481971b
Create Date: 2026-07-26 15:05:02.611216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937ff52a491b'
down_revision: Union[str, Sequence[str], None] = '67260481971b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_message_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('line_message_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('image', 'video', 'audio', 'file', name='linemessageattachmenttype'), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['line_message_id'], ['line_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_message_attachments_line_message_id'), 'line_message_attachments', ['line_message_id'], unique=False)
    op.add_column('line_messages', sa.Column('message_type', sa.Enum('text', 'image', 'video', 'audio', 'file', name='linemessagetype'), nullable=False))
    op.add_column('line_messages', sa.Column('line_platform_message_id', sa.String(), nullable=False))
    op.alter_column('line_messages', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_line_messages_line_platform_message_id'), 'line_messages', ['line_platform_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_messages_line_platform_message_id'), table_name='line_messages')
    op.alter_column('line_messages', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('line_messages', 'line_platform_message_id')
    op.drop_column('line_messages', 'message_type')
    op.drop_index(op.f('ix_line_message_attachments_line_message_id'), table_name='line_message_attachments')
    op.drop_table('line_message_attachments')
    # ### end Alembic commands ###
