"""change line_group_id to line_chat_id

Revision ID: 99175e65b8b4
Revises: 474519fb3cfb
Create Date: 2026-07-18 14:56:32.828445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99175e65b8b4'
down_revision: Union[str, Sequence[str], None] = '474519fb3cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_conversations', sa.Column('line_chat_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_line_conversations_line_group_id'), table_name='line_conversations')
    op.create_index(op.f('ix_line_conversations_line_chat_id'), 'line_conversations', ['line_chat_id'], unique=True)
    op.drop_column('line_conversations', 'line_group_id')
    op.add_column('line_messages', sa.Column('line_chat_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_line_messages_line_group_id'), table_name='line_messages')
    op.create_index(op.f('ix_line_messages_line_chat_id'), 'line_messages', ['line_chat_id'], unique=False)
    op.drop_column('line_messages', 'line_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_messages', sa.Column('line_group_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_line_messages_line_chat_id'), table_name='line_messages')
    op.create_index(op.f('ix_line_messages_line_group_id'), 'line_messages', ['line_group_id'], unique=False)
    op.drop_column('line_messages', 'line_chat_id')
    op.add_column('line_conversations', sa.Column('line_group_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_line_conversations_line_chat_id'), table_name='line_conversations')
    op.create_index(op.f('ix_line_conversations_line_group_id'), 'line_conversations', ['line_group_id'], unique=True)
    op.drop_column('line_conversations', 'line_chat_id')
    # ### end Alembic commands ###
