"""work items and line messages

Revision ID: a5ee73db95d8
Revises: 55bac9ff6052
Create Date: 2026-07-03 05:18:53.246449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ee73db95d8'
down_revision: Union[str, Sequence[str], None] = '55bac9ff6052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('line_user_id', sa.String(), nullable=True),
    sa.Column('line_group_id', sa.String(), nullable=True),
    sa.Column('sender_line_user_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_messages_company_id'), 'line_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_line_messages_line_group_id'), 'line_messages', ['line_group_id'], unique=False)
    op.create_index(op.f('ix_line_messages_line_user_id'), 'line_messages', ['line_user_id'], unique=False)
    op.create_table('work_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('new', 'scheduled', 'in_progress', 'closed', name='workitemstatus'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_items_assignee_id'), 'work_items', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_work_items_id'), 'work_items', ['id'], unique=False)
    op.create_index(op.f('ix_work_items_project_id'), 'work_items', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_items_project_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_assignee_id'), table_name='work_items')
    op.drop_table('work_items')
    op.drop_index(op.f('ix_line_messages_line_user_id'), table_name='line_messages')
    op.drop_index(op.f('ix_line_messages_line_group_id'), table_name='line_messages')
    op.drop_index(op.f('ix_line_messages_company_id'), table_name='line_messages')
    op.drop_table('line_messages')
    # ### end Alembic commands ###
