"""remove action items

Revision ID: ae234f1ba772
Revises: c54af9d0ca24
Create Date: 2026-07-16 02:28:48.337920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae234f1ba772'
down_revision: Union[str, Sequence[str], None] = 'c54af9d0ca24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_items_assignee_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_project_id'), table_name='action_items')
    op.drop_table('action_items')
    op.create_index(op.f('ix_conversation_items_created_at'), 'conversation_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_items_updated_at'), 'conversation_items', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_items_updated_at'), table_name='conversation_items')
    op.drop_index(op.f('ix_conversation_items_created_at'), table_name='conversation_items')
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assignee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('new', 'scheduled', 'in_progress', 'closed', name='actionitemstatus'), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('source_message_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('work_items_assignee_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('work_items_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('work_items_pkey'))
    )
    op.create_index(op.f('ix_action_items_project_id'), 'action_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_action_items_id'), 'action_items', ['id'], unique=False)
    op.create_index(op.f('ix_action_items_assignee_id'), 'action_items', ['assignee_id'], unique=False)
    # ### end Alembic commands ###
