"""remove template_field_id

Revision ID: aef1146d6525
Revises: 1ffba63c21d5
Create Date: 2026-02-13 21:50:52.234745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef1146d6525'
down_revision: Union[str, Sequence[str], None] = '1ffba63c21d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_fields', sa.Column('description', sa.String(), nullable=False))
    op.alter_column('report_fields', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_report_fields_template_field_id'), table_name='report_fields')
    op.drop_constraint(op.f('report_fields_template_field_id_fkey'), 'report_fields', type_='foreignkey')
    op.drop_column('report_fields', 'template_field_id')
    op.alter_column('report_template_fields', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_template_fields', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('report_fields', sa.Column('template_field_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('report_fields_template_field_id_fkey'), 'report_fields', 'report_template_fields', ['template_field_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_report_fields_template_field_id'), 'report_fields', ['template_field_id'], unique=False)
    op.alter_column('report_fields', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('report_fields', 'description')
    # ### end Alembic commands ###
