"""work items to action items

Revision ID: b2a8bca9c50b
Revises: dae4a91480e6
Create Date: 2026-07-04 14:00:21.158330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2a8bca9c50b'
down_revision: Union[str, Sequence[str], None] = 'dae4a91480e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_message_text', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('new', 'scheduled', 'in_progress', 'closed', name='actionitemstatus'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_assignee_id'), 'action_items', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_action_items_id'), 'action_items', ['id'], unique=False)
    op.create_index(op.f('ix_action_items_project_id'), 'action_items', ['project_id'], unique=False)
    op.drop_index(op.f('ix_work_items_assignee_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_project_id'), table_name='work_items')
    op.drop_table('work_items')
    op.add_column('line_messages', sa.Column('triggered_action_item_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_line_messages_triggered_work_item_id'), table_name='line_messages')
    op.create_index(op.f('ix_line_messages_triggered_action_item_id'), 'line_messages', ['triggered_action_item_id'], unique=False)
    op.drop_constraint(op.f('line_messages_triggered_work_item_id_fkey'), 'line_messages', type_='foreignkey')
    op.create_foreign_key(None, 'line_messages', 'action_items', ['triggered_action_item_id'], ['id'], ondelete='SET NULL')
    op.drop_column('line_messages', 'triggered_work_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_messages', sa.Column('triggered_work_item_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'line_messages', type_='foreignkey')
    op.create_foreign_key(op.f('line_messages_triggered_work_item_id_fkey'), 'line_messages', 'work_items', ['triggered_work_item_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_line_messages_triggered_action_item_id'), table_name='line_messages')
    op.create_index(op.f('ix_line_messages_triggered_work_item_id'), 'line_messages', ['triggered_work_item_id'], unique=False)
    op.drop_column('line_messages', 'triggered_action_item_id')
    op.create_table('work_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assignee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('new', 'scheduled', 'in_progress', 'closed', name='workitemstatus'), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('source_message_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('work_items_assignee_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('work_items_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('work_items_pkey'))
    )
    op.create_index(op.f('ix_work_items_project_id'), 'work_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_items_id'), 'work_items', ['id'], unique=False)
    op.create_index(op.f('ix_work_items_assignee_id'), 'work_items', ['assignee_id'], unique=False)
    op.drop_index(op.f('ix_action_items_project_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_assignee_id'), table_name='action_items')
    op.drop_table('action_items')
    # ### end Alembic commands ###
