"""add report image dimensions

Revision ID: b301e02af67c
Revises: 50102249365f
Create Date: 2026-03-18 02:53:01.222803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b301e02af67c'
down_revision: Union[str, Sequence[str], None] = '50102249365f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('report_images', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_images', 'height')
    op.drop_column('report_images', 'width')
    # ### end Alembic commands ###
