"""remove key again again

Revision ID: b575409a7603
Revises: 41fb14d11e70
Create Date: 2026-08-19 23:52:20.823677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b575409a7603'
down_revision: Union[str, Sequence[str], None] = '41fb14d11e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_object_definitions', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_object_definitions', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
