"""add triggered_work_item to line message

Revision ID: bdddcdf06b05
Revises: a5ee73db95d8
Create Date: 2026-07-03 12:16:53.008917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdddcdf06b05'
down_revision: Union[str, Sequence[str], None] = 'a5ee73db95d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_messages', sa.Column('triggered_work_item', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_messages', 'triggered_work_item')
    # ### end Alembic commands ###
