"""add is_target_owned

Revision ID: c1b180f8b2f4
Revises: d3066a8992e1
Create Date: 2026-09-08 05:26:17.893377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b180f8b2f4'
down_revision: Union[str, Sequence[str], None] = 'd3066a8992e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_relationship_definitions', sa.Column('is_target_owned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_relationship_definitions', 'is_target_owned')
    # ### end Alembic commands ###
