"""channel access token error

Revision ID: c3d53e109019
Revises: 154bcc859379
Create Date: 2026-08-09 05:15:06.035468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d53e109019'
down_revision: Union[str, Sequence[str], None] = '154bcc859379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('line_channel_access_token_invalid', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'line_channel_access_token_invalid')
    # ### end Alembic commands ###
