"""add images

Revision ID: c4841460e711
Revises: 00f8bea165ff
Create Date: 2026-03-10 02:44:35.188209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4841460e711'
down_revision: Union[str, Sequence[str], None] = '00f8bea165ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_image_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_image_tags_company_id'), 'report_image_tags', ['company_id'], unique=False)
    op.create_index(op.f('ix_report_image_tags_id'), 'report_image_tags', ['id'], unique=False)
    op.create_table('report_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_images_id'), 'report_images', ['id'], unique=False)
    op.create_index(op.f('ix_report_images_report_id'), 'report_images', ['report_id'], unique=False)
    op.create_table('report_image_tag_links',
    sa.Column('report_image_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['report_image_id'], ['report_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['report_image_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_image_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_image_tag_links')
    op.drop_index(op.f('ix_report_images_report_id'), table_name='report_images')
    op.drop_index(op.f('ix_report_images_id'), table_name='report_images')
    op.drop_table('report_images')
    op.drop_index(op.f('ix_report_image_tags_id'), table_name='report_image_tags')
    op.drop_index(op.f('ix_report_image_tags_company_id'), table_name='report_image_tags')
    op.drop_table('report_image_tags')
    # ### end Alembic commands ###
