"""line message conversation item link

Revision ID: c54af9d0ca24
Revises: 713e722094c9
Create Date: 2026-07-16 01:59:48.839386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54af9d0ca24'
down_revision: Union[str, Sequence[str], None] = '713e722094c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_message_conversation_item_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('line_message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_item_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_item_id'], ['conversation_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_message_id'], ['line_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_message_id', 'conversation_item_id', name='uq_line_message_conversation_item')
    )
    op.create_index(op.f('ix_line_message_conversation_item_links_conversation_item_id'), 'line_message_conversation_item_links', ['conversation_item_id'], unique=False)
    op.create_index(op.f('ix_line_message_conversation_item_links_line_message_id'), 'line_message_conversation_item_links', ['line_message_id'], unique=False)
    op.drop_index(op.f('ix_line_messages_triggered_action_item_id'), table_name='line_messages')
    op.drop_constraint(op.f('line_messages_triggered_action_item_id_fkey'), 'line_messages', type_='foreignkey')
    op.drop_column('line_messages', 'triggered_action_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_messages', sa.Column('triggered_action_item_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('line_messages_triggered_action_item_id_fkey'), 'line_messages', 'action_items', ['triggered_action_item_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_line_messages_triggered_action_item_id'), 'line_messages', ['triggered_action_item_id'], unique=False)
    op.drop_index(op.f('ix_line_message_conversation_item_links_line_message_id'), table_name='line_message_conversation_item_links')
    op.drop_index(op.f('ix_line_message_conversation_item_links_conversation_item_id'), table_name='line_message_conversation_item_links')
    op.drop_table('line_message_conversation_item_links')
    # ### end Alembic commands ###
