"""add created_by to reports

Revision ID: c76e26fecd0a
Revises: 79bb19a66a3d
Create Date: 2026-05-28 09:15:35.478146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76e26fecd0a'
down_revision: Union[str, Sequence[str], None] = '79bb19a66a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_reports_created_by'), 'reports', ['created_by'], unique=False)
    op.create_foreign_key(None, 'reports', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_created_by'), table_name='reports')
    op.drop_column('reports', 'created_by')
    # ### end Alembic commands ###
