"""line image link

Revision ID: cb6113f0d3c6
Revises: 707b54c07572
Create Date: 2026-07-29 15:36:46.059111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb6113f0d3c6'
down_revision: Union[str, Sequence[str], None] = '707b54c07572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_message_image_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('line_message_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_message_id'], ['line_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_message_id', 'image_id', name='uq_line_message_image')
    )
    op.create_index(op.f('ix_line_message_image_links_image_id'), 'line_message_image_links', ['image_id'], unique=False)
    op.create_index(op.f('ix_line_message_image_links_line_message_id'), 'line_message_image_links', ['line_message_id'], unique=False)
    op.drop_index(op.f('ix_line_message_attachments_line_message_id'), table_name='line_message_attachments')
    op.drop_table('line_message_attachments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_message_attachments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('line_message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('image', 'video', 'audio', 'file', name='linemessageattachmenttype'), autoincrement=False, nullable=False),
    sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['line_message_id'], ['line_messages.id'], name=op.f('line_message_attachments_line_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('line_message_attachments_pkey'))
    )
    op.create_index(op.f('ix_line_message_attachments_line_message_id'), 'line_message_attachments', ['line_message_id'], unique=False)
    op.drop_index(op.f('ix_line_message_image_links_line_message_id'), table_name='line_message_image_links')
    op.drop_index(op.f('ix_line_message_image_links_image_id'), table_name='line_message_image_links')
    op.drop_table('line_message_image_links')
    # ### end Alembic commands ###
