"""remove project users

Revision ID: d3066a8992e1
Revises: 214981cc221c
Create Date: 2026-09-02 05:52:35.140471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3066a8992e1'
down_revision: Union[str, Sequence[str], None] = '214981cc221c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_user_links_id'), table_name='project_user_links')
    op.drop_index(op.f('ix_project_user_links_project_id'), table_name='project_user_links')
    op.drop_index(op.f('ix_project_user_links_user_id'), table_name='project_user_links')
    op.drop_table('project_user_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_user_links',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_user_links_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_user_links_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_user_links_pkey')),
    sa.UniqueConstraint('user_id', 'project_id', name=op.f('uq_project_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_project_user_links_user_id'), 'project_user_links', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_user_links_project_id'), 'project_user_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_user_links_id'), 'project_user_links', ['id'], unique=False)
    # ### end Alembic commands ###
