"""add image created_at

Revision ID: d3a718fd093b
Revises: b301e02af67c
Create Date: 2026-03-18 06:35:11.759108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a718fd093b'
down_revision: Union[str, Sequence[str], None] = 'b301e02af67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_images', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_images', 'created_at')
    # ### end Alembic commands ###
