"""image tag link unique constraint

Revision ID: d9bb78108868
Revises: dd0d013aebe2
Create Date: 2026-03-31 02:13:18.371784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bb78108868'
down_revision: Union[str, Sequence[str], None] = 'dd0d013aebe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_report_image_tag', 'report_image_tag_links', ['report_image_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_report_image_tag', 'report_image_tag_links', type_='unique')
    # ### end Alembic commands ###
