"""work items source text

Revision ID: dae4a91480e6
Revises: bdddcdf06b05
Create Date: 2026-07-04 13:35:40.512002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae4a91480e6'
down_revision: Union[str, Sequence[str], None] = 'bdddcdf06b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_messages', sa.Column('triggered_work_item_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_line_messages_triggered_work_item_id'), 'line_messages', ['triggered_work_item_id'], unique=False)
    op.create_foreign_key(None, 'line_messages', 'work_items', ['triggered_work_item_id'], ['id'], ondelete='SET NULL')
    op.drop_column('line_messages', 'triggered_work_item')
    op.add_column('work_items', sa.Column('source_message_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_items', 'source_message_text')
    op.add_column('line_messages', sa.Column('triggered_work_item', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'line_messages', type_='foreignkey')
    op.drop_index(op.f('ix_line_messages_triggered_work_item_id'), table_name='line_messages')
    op.drop_column('line_messages', 'triggered_work_item_id')
    # ### end Alembic commands ###
