"""add created_by to report_images

Revision ID: dd0d013aebe2
Revises: 098604d823c7
Create Date: 2026-03-31 00:54:00.049320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0d013aebe2'
down_revision: Union[str, Sequence[str], None] = '098604d823c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_images', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_report_images_created_by'), 'report_images', ['created_by'], unique=False)
    op.create_foreign_key(None, 'report_images', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_images', type_='foreignkey')
    op.drop_index(op.f('ix_report_images_created_by'), table_name='report_images')
    op.drop_column('report_images', 'created_by')
    # ### end Alembic commands ###
