"""sort orders

Revision ID: e0cc04799a0b
Revises: 1292575ce0bd
Create Date: 2026-08-18 20:07:09.397637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0cc04799a0b'
down_revision: Union[str, Sequence[str], None] = '1292575ce0bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field_definitions', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('custom_relationship_definitions', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_relationship_definitions', 'sort_order')
    op.drop_column('custom_field_definitions', 'sort_order')
    # ### end Alembic commands ###
