"""update report image links

Revision ID: f466f96cbc22
Revises: 481d8a2085c2
Create Date: 2026-07-28 13:48:52.024718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f466f96cbc22'
down_revision: Union[str, Sequence[str], None] = '481d8a2085c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_image_tag_links_image_id'), 'image_tag_links', ['image_id'], unique=False)
    op.create_index(op.f('ix_image_tag_links_tag_id'), 'image_tag_links', ['tag_id'], unique=False)
    op.create_index('ix_report_image_links_report_image', 'report_image_links', ['report_id', 'image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_image_links_report_image', table_name='report_image_links')
    op.drop_index(op.f('ix_image_tag_links_tag_id'), table_name='image_tag_links')
    op.drop_index(op.f('ix_image_tag_links_image_id'), table_name='image_tag_links')
    # ### end Alembic commands ###
