"""add description to images

Revision ID: ffa099106ccf
Revises: d3a718fd093b
Create Date: 2026-03-23 02:59:16.903748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa099106ccf'
down_revision: Union[str, Sequence[str], None] = 'd3a718fd093b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_images', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_images', 'description')
    # ### end Alembic commands ###
