name: Deploy Image Worker

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO: ${{ secrets.ECR_REPOSITORY_DEV }}

on:
  workflow_dispatch:

jobs:
  deploy-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Set worker image tag
        run: echo "WORKER_IMAGE_TAG=worker-${{ github.sha }}" >> $GITHUB_ENV

      - name: Set worker image URI
        run: echo "WORKER_IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$WORKER_IMAGE_TAG" >> $GITHUB_ENV

      - name: Build worker image
        run: |
          docker build -f Dockerfile.worker -t $ECR_REPO:$WORKER_IMAGE_TAG .

      - name: Tag worker image
        run: |
          docker tag $ECR_REPO:$WORKER_IMAGE_TAG $WORKER_IMAGE_URI

      - name: Push worker image
        run: |
          docker push $WORKER_IMAGE_URI

      - name: Register new worker task definition
        run: |
          TASK_DEF=$(aws ecs describe-task-definition \
            --task-definition ${{ secrets.ECS_IMAGE_WORKER_TASK_DEFINITION_DEV }} \
            --query taskDefinition)

          echo "$TASK_DEF" > worker-task-def.json

          NEW_TASK_DEF=$(jq --arg IMAGE "$WORKER_IMAGE_URI" '
            .containerDefinitions[0].image = $IMAGE
            | del(
                .taskDefinitionArn,
                .revision,
                .status,
                .requiresAttributes,
                .compatibilities,
                .registeredAt,
                .registeredBy
              )
          ' worker-task-def.json)

          echo "$NEW_TASK_DEF" > new-worker-task-def.json

          NEW_WORKER_TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-worker-task-def.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "NEW_WORKER_TASK_DEF_ARN=$NEW_WORKER_TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Update worker ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_DEV }} \
            --service ${{ secrets.ECS_IMAGE_WORKER_SERVICE_DEV }} \
            --task-definition $NEW_WORKER_TASK_DEF_ARN
